In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
print("Libraries loaded")

Libraries loaded


In [5]:
correct_labels = np.load('../data/LSTM Exercise Classification Push Up Videos/labels/correct.npy')
incorrect_labels = np.load('../data/LSTM Exercise Classification Push Up Videos/labels/incorrect.npy')

In [6]:
print("Correct shape:", correct_labels.shape)
print("Incorrect shape:", incorrect_labels.shape)
print("\nCorrect sample:", correct_labels[:5])
print("Incorrect sample:", incorrect_labels[:5])

Correct shape: (50, 150, 66)
Incorrect shape: (50, 150, 66)

Correct sample: [[[0.72996914 0.56077725 0.74594104 ... 0.81228918 0.21159618 0.83733207]
  [0.73164785 0.56872994 0.74757385 ... 0.8123799  0.21266708 0.83732045]
  [0.73250574 0.57444197 0.7492429  ... 0.8123861  0.21350794 0.83735514]
  ...
  [0.73464316 0.54085928 0.74885237 ... 0.81421196 0.21973976 0.84286374]
  [0.73436219 0.54055965 0.74861085 ... 0.81420612 0.21980353 0.8428756 ]
  [0.73427397 0.5405091  0.74849886 ... 0.81425315 0.21985166 0.84288704]]

 [[0.68008339 0.43787903 0.69121832 ... 0.76896226 0.09707132 0.80516219]
  [0.67687911 0.44226807 0.68904769 ... 0.76963049 0.09459491 0.81194407]
  [0.67511827 0.4464595  0.6874541  ... 0.77116996 0.09301362 0.81571895]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[0.87562293 0.515

In [7]:
print("Anzahl korrekte Videos: (erwartet 50)", len(correct_labels))
print("Anzahl inkorrekte Videos: (erwartet 50)", len(incorrect_labels))
print("Ein einzelner Frame (Video 0, Frame 0):", correct_labels[0][0])

Anzahl korrekte Videos: (erwartet 50) 50
Anzahl inkorrekte Videos: (erwartet 50) 50
Ein einzelner Frame (Video 0, Frame 0): [0.72996914 0.56077725 0.74594104 0.54692626 0.74696243 0.54494941
 0.74790233 0.54260212 0.74234235 0.5403949  0.74048167 0.53386486
 0.7383284  0.52699327 0.73717588 0.50382692 0.72447073 0.48372582
 0.7137832  0.55594075 0.70855528 0.54521215 0.67817503 0.50095642
 0.62091261 0.48547998 0.65194756 0.67332304 0.56140971 0.70382816
 0.64930218 0.86427331 0.55598056 0.91087788 0.67077017 0.88565266
 0.57615769 0.9489373  0.66725749 0.88829607 0.58598775 0.93967062
 0.65531951 0.88401693 0.58304816 0.92534852 0.46318966 0.58108163
 0.42866153 0.56014401 0.3432712  0.66612506 0.31225699 0.66874546
 0.23126633 0.70403534 0.19969836 0.72829711 0.20178242 0.6894486
 0.17596252 0.71090126 0.23747823 0.81228918 0.21159618 0.83733207]


In [8]:
print("Aufbau der Frames: x0 y0, x1 y1, ... xn yn")
print("x Koordinate ist am Index 2n; y Koordinate ist am Index 2n+1")
print("Das bedeutet: Das 0te Landmark ist bei Index 0 und 1, das 1te bei Index 2 und 3 usw.")
print("Alle 33 Landmarks sind folgendermaßen aufgeteilt: https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker")

Aufbau der Frames: x0 y0, x1 y1, ... xn yn
x Koordinate ist am Index 2n; y Koordinate ist am Index 2n+1
Das bedeutet: Das 0te Landmark ist bei Index 0 und 1, das 1te bei Index 2 und 3 usw.
Alle 33 Landmarks sind folgendermaßen aufgeteilt: https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker


In [9]:
import os

correct_path = '../data/LSTM Exercise Classification Push Up Videos/Correct sequence'
incorrect_path = '../data/LSTM Exercise Classification Push Up Videos/Wrong sequence'

correct_videos = os.listdir(correct_path)
incorrect_videos = os.listdir(incorrect_path)

print("Anzahl korrekte Videos: (erwartet 50)", len(correct_videos))
print("Anzahl inkorrekte Videos (erwartet 50):", len(incorrect_videos))
print("\nBeispiele korrekt:", correct_videos[:3])
print("Beispiele inkorrekt:", incorrect_videos[:3])

Anzahl korrekte Videos: (erwartet 50) 50
Anzahl inkorrekte Videos (erwartet 50): 50

Beispiele korrekt: ['Copy of push up 138.mp4', 'Copy of push up 113.mp4', 'Copy of push up 102.mp4']
Beispiele inkorrekt: ['Copy of push up 105.mp4', '7.mp4', '6.mp4']
