In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
print("Libraries loaded")

Libraries loaded


In [5]:
correct_labels = np.load('../data/LSTM Exercise Classification Push Up Videos/labels/correct.npy')
incorrect_labels = np.load('../data/LSTM Exercise Classification Push Up Videos/labels/incorrect.npy')

In [6]:
print("Correct shape:", correct_labels.shape)
print("Incorrect shape:", incorrect_labels.shape)
print("\nCorrect sample:", correct_labels[:5])
print("Incorrect sample:", incorrect_labels[:5])

Correct shape: (50, 150, 66)
Incorrect shape: (50, 150, 66)

Correct sample: [[[0.72996914 0.56077725 0.74594104 ... 0.81228918 0.21159618 0.83733207]
  [0.73164785 0.56872994 0.74757385 ... 0.8123799  0.21266708 0.83732045]
  [0.73250574 0.57444197 0.7492429  ... 0.8123861  0.21350794 0.83735514]
  ...
  [0.73464316 0.54085928 0.74885237 ... 0.81421196 0.21973976 0.84286374]
  [0.73436219 0.54055965 0.74861085 ... 0.81420612 0.21980353 0.8428756 ]
  [0.73427397 0.5405091  0.74849886 ... 0.81425315 0.21985166 0.84288704]]

 [[0.68008339 0.43787903 0.69121832 ... 0.76896226 0.09707132 0.80516219]
  [0.67687911 0.44226807 0.68904769 ... 0.76963049 0.09459491 0.81194407]
  [0.67511827 0.4464595  0.6874541  ... 0.77116996 0.09301362 0.81571895]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[0.87562293 0.515

In [7]:
print("Anzahl korrekte Videos: (erwartet 50)", len(correct_labels))
print("Anzahl inkorrekte Videos: (erwartet 50)", len(incorrect_labels))
print("Ein einzelner Frame (Video 0, Frame 0):", correct_labels[0][0])

Anzahl korrekte Videos: (erwartet 50) 50
Anzahl inkorrekte Videos: (erwartet 50) 50
Ein einzelner Frame (Video 0, Frame 0): [0.72996914 0.56077725 0.74594104 0.54692626 0.74696243 0.54494941
 0.74790233 0.54260212 0.74234235 0.5403949  0.74048167 0.53386486
 0.7383284  0.52699327 0.73717588 0.50382692 0.72447073 0.48372582
 0.7137832  0.55594075 0.70855528 0.54521215 0.67817503 0.50095642
 0.62091261 0.48547998 0.65194756 0.67332304 0.56140971 0.70382816
 0.64930218 0.86427331 0.55598056 0.91087788 0.67077017 0.88565266
 0.57615769 0.9489373  0.66725749 0.88829607 0.58598775 0.93967062
 0.65531951 0.88401693 0.58304816 0.92534852 0.46318966 0.58108163
 0.42866153 0.56014401 0.3432712  0.66612506 0.31225699 0.66874546
 0.23126633 0.70403534 0.19969836 0.72829711 0.20178242 0.6894486
 0.17596252 0.71090126 0.23747823 0.81228918 0.21159618 0.83733207]


In [8]:
print("Aufbau der Frames: x0 y0, x1 y1, ... xn yn")
print("x Koordinate ist am Index 2n; y Koordinate ist am Index 2n+1")
print("Das bedeutet: Das 0te Landmark ist bei Index 0 und 1, das 1te bei Index 2 und 3 usw.")
print("Alle 33 Landmarks sind folgendermaßen aufgeteilt: https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker")

Aufbau der Frames: x0 y0, x1 y1, ... xn yn
x Koordinate ist am Index 2n; y Koordinate ist am Index 2n+1
Das bedeutet: Das 0te Landmark ist bei Index 0 und 1, das 1te bei Index 2 und 3 usw.
Alle 33 Landmarks sind folgendermaßen aufgeteilt: https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker


In [9]:
import os

correct_path = '../data/LSTM Exercise Classification Push Up Videos/Correct sequence'
incorrect_path = '../data/LSTM Exercise Classification Push Up Videos/Wrong sequence'

correct_videos = os.listdir(correct_path)
incorrect_videos = os.listdir(incorrect_path)

print("Anzahl korrekte Videos: (erwartet 50)", len(correct_videos))
print("Anzahl inkorrekte Videos (erwartet 50):", len(incorrect_videos))
print("\nBeispiele korrekt:", correct_videos[:3])
print("Beispiele inkorrekt:", incorrect_videos[:3])

Anzahl korrekte Videos: (erwartet 50) 50
Anzahl inkorrekte Videos (erwartet 50): 50

Beispiele korrekt: ['Copy of push up 138.mp4', 'Copy of push up 113.mp4', 'Copy of push up 102.mp4']
Beispiele inkorrekt: ['Copy of push up 105.mp4', '7.mp4', '6.mp4']


In [10]:
import numpy as np

# berechnet den Winkel am Punkt b, also am Scheitelpunkt
# das ist später wichtig um zum Beispiel den Winkel von der Beugung im Ellenbogen zu messen

def calculate_angles(a, b, c):

    # a, b und c sind jeweils die x und y Koordinaten

    a = np.array(a)
    b = np.array(b)
    c = np.array(c)

    # Vektoren vom Scheitelpunkt aus 
    
    vector_ab = a - b
    vector_cb = c - b

    # Skalarprodukt und Vektorlängen

    dot = np.dot(vector_ab, vector_cb)
    norm_ab = np.linalg.norm(vector_ab)
    norm_cb = np.linalg.norm(vector_cb)

    #Skalarprodukt durch das Produkt beider Vektorlänger, return: Wert zwischen -1 und 1 -> für Wertebereich für Cosinus 

    cos_angle = dot / (norm_ab * norm_cb)

    #Auf-/Abrunden von Werten für Stabilität der Endwerte (Sicherheitsnetz)
    cos_angle = np.clip(cos_angle, -1.0, 1.0) 

    #Den Cosinuswert mit arccos in Radiant Wert umrechnen, und diesen dann mithilfe von .degrees in Winkel Wert
    angle = np.degrees(np.arccos(cos_angle))

    return angle

    

In [11]:
# Test: Winkel von Ellenbogen testen beim ausgestrecktem Arm -> sollte 180 Grad ergeben

schulter180 =   [0, 2]  # . |
ellenbogen180 = [0, 1]  # . O
handgelenk180 = [0, 0]  # . |

# a = schulter, b = ellenbogen, c = handgelenk
winkel180 = calculate_angles(schulter180, ellenbogen180, handgelenk180)
print("Winkel gestreckter Arm (erwartet 180): ", winkel180)

#-------
# Test: Winkel von Ellenbogen testen beim rechwinkligem Arm -> sollte 90 Grad ergeben

schulter90 =   [0, 1]  # . |
ellenbogen90 = [0, 0]  # — O
handgelenk90 = [1, 0]  # . .

winkel90 = calculate_angles(schulter90, ellenbogen90, handgelenk90)
print("Winkel rechwinkliger Arm (erwartet 90): ", winkel90)

Winkel gestreckter Arm (erwartet 180):  180.0
Winkel rechwinkliger Arm (erwartet 90):  90.0


In [12]:
correct_labels[0][0]

array([0.72996914, 0.56077725, 0.74594104, 0.54692626, 0.74696243,
       0.54494941, 0.74790233, 0.54260212, 0.74234235, 0.5403949 ,
       0.74048167, 0.53386486, 0.7383284 , 0.52699327, 0.73717588,
       0.50382692, 0.72447073, 0.48372582, 0.7137832 , 0.55594075,
       0.70855528, 0.54521215, 0.67817503, 0.50095642, 0.62091261,
       0.48547998, 0.65194756, 0.67332304, 0.56140971, 0.70382816,
       0.64930218, 0.86427331, 0.55598056, 0.91087788, 0.67077017,
       0.88565266, 0.57615769, 0.9489373 , 0.66725749, 0.88829607,
       0.58598775, 0.93967062, 0.65531951, 0.88401693, 0.58304816,
       0.92534852, 0.46318966, 0.58108163, 0.42866153, 0.56014401,
       0.3432712 , 0.66612506, 0.31225699, 0.66874546, 0.23126633,
       0.70403534, 0.19969836, 0.72829711, 0.20178242, 0.6894486 ,
       0.17596252, 0.71090126, 0.23747823, 0.81228918, 0.21159618,
       0.83733207])

In [13]:
print("Nun berechne Ich die relevanten Winkel für eine Liegestütz, um die Anzahl an Rohdaten zu reduzieren (statt 66 bspw. 4)")

# Im MediaPipe sind die Landmarks für Körperpartien vorbesimmt (siehe Link oben)
# Mit der oben genannten Formel für die x/y Koordinaten für jeden Landmark bestimme ich die Koordinaten der wichtigen Körperpartien
# Am Ende will ich die relevanten Winkel erhalten, um wichtige Kriterien für eine korrekte/unkorrekte Liegestütz bestimmen zu können
""" dazu zählt:
      1. Rücken gerade
      2. Ellenbogen 45 Grad vom Körper
      3. Volle Tiefe (genau der Winkel: Schulter, Ellenbogen & Handgelenk)
      4. Arbeit nur aus den Armen, alles andere soll still bleiben (wie z.B. Kriterium 1)
"""

#Linke Schulter (Landmark 11)
xSchulterL = correct_labels[0][0][22]
ySchulterL = correct_labels[0][0][23]
SchulterLinks = [xSchulterL, ySchulterL]

#Linker Ellenbogen (Landmark 13)

xEllenbogenL = correct_labels[0][0][26]
yEllenbogenL = correct_labels[0][0][27]
EllenbogenLinks = [xEllenbogenL, yEllenbogenL]

#Linkes Handgelenk (Landmark 15)

xHandgelenkL = correct_labels[0][0][30]
yHandgelenkL = correct_labels[0][0][31]
HandgelenkLinks = [xHandgelenkL, yHandgelenkL]

WinkelTiefeLinks = calculate_angles(SchulterLinks, EllenbogenLinks, HandgelenkLinks)
print("Winkel tiefe Linker Arm (Video 0 Frame 0): ", WinkelTiefeLinks)



Nun berechne Ich die relevanten Winkel für eine Liegestütz, um die Anzahl an Rohdaten zu reduzieren (statt 66 bspw. 4)
Winkel tiefe Linker Arm (Video 0 Frame 0):  172.14189169982262


In [14]:
print("Der Winkel 172Grad hört sich logisch an: Im ersten Video Frame 0 ist die Person in ihrer Ausgangsposition (ausgestreckter Arm)")
print("die paar Grad können an den Filmumständen liegen wie der Kamera Position oder sonstiges optischen Täuschungen / Armwinkel zum Boden")

Der Winkel 172Grad hört sich logisch an: Im ersten Video Frame 0 ist die Person in ihrer Ausgangsposition (ausgestreckter Arm)
die paar Grad können an den Filmumständen liegen wie der Kamera Position oder sonstiges optischen Täuschungen / Armwinkel zum Boden


In [15]:
# Diese Methode soll alle Winkel aller Videos pro Frame berechnen und zurückgeben

def extract_angles(video_array):

# doppelt verkettete Schleife (äußere Schleife == Videos ; innere Schleife == Frames)
# initialisieren der beiden arrays für jeweils die frames pro video & array für videos selbst

    
    alle_videos = []
    for i in range(video_array.shape[0]):
        pro_video = []
        for j in range(video_array.shape[1]):

            # -------------------------------
            # Position der Körperteile pro Frame
            
            # Schulter (Landmark L=11 & R=12)

            xSchulterLinks = video_array[i][j][22]
            ySchulterLinks = video_array[i][j][23]
            xSchulterRechts = video_array[i][j][24]
            ySchulterRechts = video_array[i][j][25]

            SchulterLinks = [xSchulterLinks, ySchulterLinks]
            SchulterRechts = [xSchulterRechts, ySchulterRechts]
            

            # Ellenbogen (Landmark L=13 & R=14)
            
            xEllenbogenLinks = video_array[i][j][26]
            yEllenbogenLinks = video_array[i][j][27]
            xEllenbogenRechts = video_array[i][j][28]
            yEllenbogenRechts = video_array[i][j][29]

            EllenbogenLinks = [xEllenbogenLinks, yEllenbogenLinks]
            EllenbogenRechts = [xEllenbogenRechts, yEllenbogenRechts]

            # Handgelenk (Landmark L=15 & R=16)
            
            xHandgelenkLinks = video_array[i][j][30]
            yHandgelenkLinks = video_array[i][j][31]
            xHandgelenkRechts = video_array[i][j][32]
            yHandgelenkRechts = video_array[i][j][33]

            HandgelenkLinks = [xHandgelenkLinks, yHandgelenkLinks]
            HandgelenkRechts = [xHandgelenkRechts, yHandgelenkRechts]

             # Hüfte (Landmark L=23 & R=24)
            
            xHuefteLinks = video_array[i][j][46]
            yHuefteLinks = video_array[i][j][47]
            xHuefteRechts = video_array[i][j][48]
            yHuefteRechts = video_array[i][j][49]

            HuefteLinks = [xHuefteLinks, yHuefteLinks]
            HuefteRechts = [xHuefteRechts, yHuefteRechts]

            # Knie (Landmark L=25 & R=26)
            
            xKnieLinks = video_array[i][j][50]
            yKnieLinks = video_array[i][j][51]
            xKnieRechts = video_array[i][j][52]
            yKnieRechts = video_array[i][j][53]

            KnieLinks = [xKnieLinks, yKnieLinks]
            KnieRechts = [xKnieRechts, yKnieRechts]

            # Knöchel (Landmark L=27 & R=28)
            
            xKnoechelLinks = video_array[i][j][54]
            yKnoechelLinks = video_array[i][j][55]
            xKnoechelRechts = video_array[i][j][56]
            yKnoechelRechts = video_array[i][j][57]

            KnoechelLinks = [xKnoechelLinks, yKnoechelLinks]
            KnoechelRechts = [xKnoechelRechts, yKnoechelRechts]

            # Winkel Ellenbogen (Schulter, Ellenbogen & Handgelenk)

            WinkelEllenbogenLinks = calculate_angles(SchulterLinks, EllenbogenLinks, HandgelenkLinks)
            WinkelEllenbogenRechts = calculate_angles(SchulterRechts, EllenbogenRechts, HandgelenkRechts)

             # Winkel Rücken (Hüfte, Knie, Knöchel)

            WinkelRueckenLinks = calculate_angles(HuefteLinks, KnieLinks, KnoechelLinks)
            WinkelRueckenRechts = calculate_angles(HuefteRechts, KnieRechts, KnoechelRechts)

            # Durchschnitt für die jeweiligen Seite der Arme / Beine, weil asynchrone Ausführung der Übung ebenfalls möglich
            
            WinkelEllenbogenAvg = (WinkelEllenbogenLinks + WinkelEllenbogenRechts) / 2
            WinkelRueckenAvg = (WinkelRueckenLinks + WinkelRueckenRechts) / 2


            #Anhängen der Winkel an Array pro einzelnes Video
            
            pro_video.append([WinkelEllenbogenAvg, WinkelRueckenAvg])

        alle_videos.append(pro_video)

    return alle_videos
            

In [16]:
correct_features = extract_angles(correct_labels)
incorrect_features = extract_angles(incorrect_labels)

print("Shape correct features:", np.array(correct_features).shape)
print("Shape incorrect features:", np.array(incorrect_features).shape)

/var/folders/bd/pl944hbj61n6mpghlwvnxy5r0000gn/T/ipykernel_2426/3943561217.py:27: RuntimeWarning: invalid value encountered in scalar divide
  cos_angle = dot / (norm_ab * norm_cb)


Shape correct features: (50, 150, 2)
Shape incorrect features: (50, 150, 2)


In [17]:
# Methode um die Features zu reduzieren, sodass scikit damit arbeiten kann

def reduce_features(features_array):

    #Verwandeln in ein numpy array
    npArr = np.array(features_array)

    # durchschnitt, min & max der Winkel des gegebenen featurearrays
    #axis = 1 -> bezieht sich auf Frames
    
    durchschnittArr = npArr.mean(axis = 1)
    maxArr = npArr.max(axis = 1)
    minArr = npArr.min(axis = 1)

    #zusammenfügen zu einem Array
    npArrCombined = np.concatenate([durchschnittArr, maxArr, minArr], axis=1)

    return npArrCombined    

In [18]:
correct_reduced = reduce_features(correct_features)
incorrect_reduced = reduce_features(incorrect_features)

# erwartet: (50, 6)
print(correct_reduced.shape)

# erwartet: (50, 6)
print(incorrect_reduced.shape)

(50, 6)
(50, 6)


In [19]:
# Labels für das Modell zum trainieren
labels_correct = np.ones(50)
labels_incorrect = np.zeros(50)

labels = np.concatenate([labels_correct, labels_incorrect])

#erwartete shape: 100
print(labels)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [20]:
reduced_array = np.concatenate([correct_reduced, incorrect_reduced])

#erwartet: 100,6
print(reduced_array)

[[134.34569132 160.33285914 174.57484426 165.82083082  69.13450837
  153.23917649]
 [         nan          nan          nan          nan          nan
           nan]
 [         nan          nan          nan          nan          nan
           nan]
 [         nan          nan          nan          nan          nan
           nan]
 [         nan          nan          nan          nan          nan
           nan]
 [         nan          nan          nan          nan          nan
           nan]
 [         nan          nan          nan          nan          nan
           nan]
 [142.40020609 147.22969899 171.93882941 154.92801192  75.34548512
  142.85198665]
 [         nan          nan          nan          nan          nan
           nan]
 [         nan          nan          nan          nan          nan
           nan]
 [         nan          nan          nan          nan          nan
           nan]
 [         nan          nan          nan          nan          nan
           nan]
 [  

In [21]:
print("Beobachtung: die meisten Videos sind not a number (Padding-Problem)")
print("Lösungsansatz: .mean(), .min() & .max() mit np.nanmean(), np.nanmin & np.nanmax zu ersetzen")

#-------
# Methode um die Features zu reduzieren, sodass scikit damit arbeiten kann

def reduce_features(features_array):

    #Verwandeln in ein numpy array
    npArr = np.array(features_array)

    # durchschnitt, min & max der Winkel des gegebenen featurearrays
    #axis = 1 -> bezieht sich auf Frames

    #der Knackpunkt ist hier: hier behandeln wir das Padding-Problem
    durchschnittArr = np.nanmean(npArr, axis = 1)
    maxArr = np.nanmax(npArr, axis = 1)
    minArr = np.nanmin(npArr, axis = 1)

    #zusammenfügen zu einem Array
    npArrCombined = np.concatenate([durchschnittArr, maxArr, minArr], axis=1)

    return npArrCombined   

#------

#nun führe ich die alten Befehle ebenfalls aus, um die alten Einträge zu aktualisieren
#------

correct_reduced = reduce_features(correct_features)
incorrect_reduced = reduce_features(incorrect_features)

# erwartet: (50, 6)
print(correct_reduced.shape)

# erwartet: (50, 6)
print(incorrect_reduced.shape)

# Labels für das Modell zum trainieren
labels_correct = np.ones(50)
labels_incorrect = np.zeros(50)

labels = np.concatenate([labels_correct, labels_incorrect])

#erwartete shape: 100
print(labels)

reduced_array = np.concatenate([correct_reduced, incorrect_reduced])

#erwartet: 100,6
print(reduced_array)

#------

Beobachtung: die meisten Videos sind not a number (Padding-Problem)
Lösungsansatz: .mean(), .min() & .max() mit np.nanmean(), np.nanmin & np.nanmax zu ersetzen
(50, 6)
(50, 6)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[[134.34569132 160.33285914 174.57484426 165.82083082  69.13450837
  153.23917649]
 [132.24419296 169.79860774 173.36161706 172.82501104  52.75291108
  162.76649628]
 [140.58028591 165.22571808 175.79035042 172.90560675  58.4104887
  154.90611277]
 [132.85243044 165.21437544 173.25892324 169.85641833  58.1603384
  154.70357452]
 [136.40354697 165.60349756 174.56192877 171.61057874  55.92921548
  157.49144183]
 [145.55522046 147.49970499 165.84275886 149.55189012  81.96280683
  142.37622261]
 [134.0969153  147.548